Repository Hackathon7/Pacify-final, pull requests merged in 2022-04, with the labels that each got.

#166 added relevant images to images file folder
  images file/Articles.png
  images file/Features.png
  images file/Home.png
  images file/Quiz-Quest.png
  images file/Quiz-Result.png
Labels: GSSoC22, Level1

#167 Added project images in project images section of readme
  README.md
Labels: GSSoC22, Level1

#168 Live Chatbot added
  chatwoot.js
  css/owl.carousel.min.css
  css/stylequiz.css
  html/single.html
  index.html
  main.js
  single.html
  style.css
Labels: GSSoC22, Level3

#182 Learn more/ Single.html conflict issues and path errors resolved styles are working now
  html/single.html
Labels: GSSoC22, Level3

#190 Added hover effect on favicon
  style.css
Labels: GSSoC22, Level1

#191 Added logo in quiz section
  html/single.html
  index.html
Labels: GSSoC22, Level2

#194 Improved text-align in about-us
  style.css
Labels: GSSoC22, Level1

#193 Fixed source-link hover effect
  html/single.html
  style.css
Labels: GSSoC22, Level1

#192 LikeButton
  index.html
Labels: GSSoC22, Level2

#200 Made changes to navbar
  Login.css
  Login.html
  style.css
Labels: GSSoC22, Level1

#206 created Issue template to set a standard guide to follow for features, bugs, etc
  .github/issue_template/issue_template.md
  html/single.html
Labels: GSSoC22, Level1

#208 Added logo in quiz section
  html/quiz.html
Labels: GSSoC22, Level1

#209 Improve footer of about us
  html/single.html
  style.css
Labels: GSSoC22, Level2

#210 feature/Added hover animation to logo image
  style.css
Labels: GSSoC22, Level2

#214 deleted unncessary files and rearranged repo
  0_xLOJMAdRT8c3tQ_4
  all.min.css
  css/Login.css
  css/SignUp.css
  css/footer.css
  css/newstyle.css
  css2
  fontawesome.min.css
  html/Login.html
  html/footer.html
  images
  images file/Article-1.jpg
  index.html
  screenshots/Article-2.jpg
  scripts/script.js
Labels: GSSoC22, Level2
