Repository Hackathon7/Pacify-final, pull requests merged in 2022-05, with the labels that each got.

#218 Modified links where broken
  html/end.html
  index.html
Labels: bug, GSSoC22, Level1

#220 Made login page changes
  .DS_Store
  css/Login.css
  html/Login.html
  index.html
Labels: bug, GSSoC22, Level1

#221 Improved quiz section navbar
  html/quiz.html
Labels: enhancement, good first issue, Level1

#227 Added Favicon in all new pages
  html/Login.html
  html/diary.html
  html/end.html
  html/pomodoro.html
Labels: enhancement, GSSoC22, Level1

#232 Made carousel responsive
  .DS_Store
  images file/carousel_image_1_modified.jpeg
  images file/carousel_image_2_modified.png
  images file/carousel_image_3_modified.png
  images file/carousel_image_4_modified.jpeg
  images file/carousel_image_5.jpeg
  images file/carousel_image_5.jpg
  images file/carousel_image_5_modified.jpeg
  images file/carousel_image_5_modified.jpg
  index.html
  style.css
Labels: bug, enhancement, GSSoC22, Level2

#230 Fixed Links in login page
  html/Login.html
Labels: bug, GSSoC22, Level1

#239 take a test for depression quiz result fixed
  scripts/quiz.js
Labels: bug, GSSoC22, Level2

#248 Added learning page
  .DS_Store
  css/learning.css
  html/learning.html
  index.html
Labels: GSSoC22, Level2

#249 Improved Footer of About us Section
  html/single.html
  style.css
Labels: GSSoC22, Level1

#250 I have changed the carousel's button as shown in picture
  index.html
  style.css
Labels: enhancement, GSSoC22

#259 css final_changes
  index.html
  style.css
Labels: GSSoC22, Level1

#255 How to get help
  html/single.html
Labels: GSSoC22, Level1

#254 Improved Navbar of website
  css/Login.css
  html/Login.html
  html/blog.html
  html/learning.html
  html/quiz.html
  html/single.html
  index.html
  style.css
Labels: GSSoC22, Level1

#261 Improved Navbar of the website
  css/Login.css
  html/Login.html
  html/blog.html
  html/learning.html
  html/quiz.html
  html/single.html
  index.html
  style.css
Labels: GSSoC22, Level1
